using Content.Shared.CCVar;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;

namespace Content.Client.Options.UI.Tabs;

[GenerateTypedNameReferences]
public sealed partial class CrosshairTab : Control
{
    [Dependency] private readonly IConfigurationManager _cfg = default!;

    public CrosshairTab()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        Control.AddOptionCheckBox(CCVars.CrosshairEnabled, EnabledCheckBox);
        Control.AddOptionCheckBox(CCVars.CrosshairCenterDot, CenterDotCheckBox);
        Control.AddOptionCheckBox(CCVars.CrosshairOutline, OutlineCheckBox);
        Control.AddOptionCheckBox(CCVars.CrosshairHitFlash, HitFlashCheckBox);
        Control.AddOptionCheckBox(CCVars.CrosshairSpreadRail, SpreadRailCheckBox);
        Control.AddOptionCheckBox(CCVars.CrosshairBloomTint, BloomTintCheckBox);
        Control.AddOptionCheckBox(CCVars.CrosshairDynamicLineWidth, DynamicLineWidthCheckBox);

        Control.AddOptionColorSlider(CCVars.CrosshairColor, ColorSlider);

        Control.AddOptionPercentSlider(CCVars.CrosshairOpacity, OpacitySlider);

        Control.AddOption(new OptionSliderFloatCVar(
            Control,
            _cfg,
            CCVars.CrosshairGap,
            GapSlider,
            1f,
            20f,
            1f,
            (_, v) => v.ToString("0.0")));

        Control.AddOption(new OptionSliderFloatCVar(
            Control,
            _cfg,
            CCVars.CrosshairLength,
            LengthSlider,
            2f,
            30f,
            1f,
            (_, v) => v.ToString("0.0")));

        Control.AddOption(new OptionSliderFloatCVar(
            Control,
            _cfg,
            CCVars.CrosshairLineWidth,
            LineWidthSlider,
            0.5f,
            6f,
            1f,
            (_, v) => v.ToString("0.0")));

        Control.AddOption(new OptionSliderFloatCVar(
            Control,
            _cfg,
            CCVars.CrosshairCenterDotRadius,
            CenterDotRadiusSlider,
            1f,
            8f,
            1f,
            (_, v) => v.ToString("0.0")));

        Control.AddOption(new OptionSliderFloatCVar(
            Control,
            _cfg,
            CCVars.CrosshairOutlineThickness,
            OutlineThicknessSlider,
            0f,
            6f,
            1f,
            (_, v) => v.ToString("0.0")));

        Control.Initialize();
    }
}
