ent-ClothingUniformRandom = { "" }
    .desc = Generated by neural networks based on the latest fashion trends.
    .suffix = Random visual

ent-ClothingRandomSpawner = random colorful costume

ent-ClothingUniformRandomArmless = colorful hands-free costume

ent-ClothingUniformRandomStandard = colorful costume

ent-ClothingUniformRandomBra = colorful bra

ent-ClothingUniformRandomShorts = colorful pants

ent-ClothingUniformRandomShirt = colorful costume
