using Content.Client.Message;
using Content.Client.Resources;
using Content.Client.UserInterface.Systems.EscapeMenu;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client.Lobby.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class LobbyGui : UIScreen
    {
        [Dependency] private readonly IClientConsoleHost _consoleHost = default!;
        [Dependency] private readonly IResourceCache _resCache = default!;

        // Палитра «Доминат Ордината» — дублируется здесь локально,
        // чтобы не тянуть весь Stylesheets API в lobby code-behind.
        private static readonly Color BloodBase = Color.FromHex("#6b0f0f");
        private static readonly Color BloodBright = Color.FromHex("#9a1a1a");
        private static readonly Color PanelSurface = Color.FromHex("#2a2833");
        private static readonly Color PanelSurfaceAlt = Color.FromHex("#302e39");
        private static readonly Color ParchmentBright = Color.FromHex("#f0e8d2");
        private static readonly Color GoldBright = Color.FromHex("#d4a960");

        public LobbyGui()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);
            SetAnchorPreset(MainContainer, LayoutPreset.Wide);
            SetAnchorPreset(Background, LayoutPreset.Wide);
            SetAnchorPreset(SolidBackground, LayoutPreset.Wide);

            LobbySong.SetMarkup(Loc.GetString("lobby-state-song-no-song-text"));

            ApplyGehennaTheme();

            LeaveButton.OnPressed += _ => _consoleHost.ExecuteCommand("disconnect");
            OptionsButton.OnPressed += _ => UserInterfaceManager.GetUIController<OptionsUIController>().ToggleWindow();

            CollapseButton.OnPressed += _ => TogglePanel(false);
            ExpandButton.OnPressed += _ => TogglePanel(true);
        }

        /// <summary>
        ///     Пришивает к лобби «досье»-визуал: классификационную плашку,
        ///     заглавный шрифт Yeseva One, оттенки пергамента/крови/золота.
        /// </summary>
        private void ApplyGehennaTheme()
        {
            // 0. Сплошной тёмный фон — «глубокий уголь».
            SolidBackground.PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = Color.FromHex("#0a0a0c"),
            };

            LeftSideTop.PanelOverride = CreateDocumentPanel(PanelSurface);
            LeftBottomPanel.PanelOverride = CreateDocumentPanel(PanelSurface);
            RightSide.PanelOverride = CreateDocumentPanel(PanelSurfaceAlt);
            ExpandPanel.PanelOverride = CreateDocumentPanel(PanelSurfaceAlt);

            // 1. Классификационная плашка — фон «кровь», верх/низ ярче, текст пергамент.
            ClassificationStrip.PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = BloodBase,
                BorderColor = BloodBright,
                BorderThickness = new Thickness(0, 0, 0, 1),
                ContentMarginTopOverride = 2,
                ContentMarginBottomOverride = 2,
            };

            var ptSansBold = _resCache.GetFont("/Fonts/PTSans/PTSans-Bold.ttf", 11);
            ClassificationLabel.FontOverride = ptSansBold;
            ClassificationLabel.FontColorOverride = ParchmentBright;
            ClassificationLabel.Text = Loc.GetString("lobby-gehenna-classification");

            // 2. Название сервера — Yeseva One, ярко-золотой.
            var yeseva = _resCache.GetFont("/Fonts/YesevaOne/YesevaOne-Regular.ttf", 28);
            ServerName.FontOverride = yeseva;
            ServerName.FontColorOverride = GoldBright;
        }

        private StyleBoxTexture CreateDocumentPanel(Color tint)
        {
            var panelTex = _resCache.GetTexture("/Textures/Interface/Nano/button.svg.96dpi.png");
            var box = new StyleBoxTexture
            {
                Texture = panelTex,
                Modulate = tint,
            };

            box.SetPatchMargin(StyleBox.Margin.All, 10);
            return box;
        }

        public void SwitchState(LobbyGuiState state)
        {
            DefaultState.Visible = false;
            CharacterSetupState.Visible = false;

            switch (state)
            {
                case LobbyGuiState.Default:
                    DefaultState.Visible = true;
                    RightSide.Visible = true;
                    break;
                case LobbyGuiState.CharacterSetup:
                    CharacterSetupState.Visible = true;

                    var actualWidth = (float) UserInterfaceManager.RootControl.PixelWidth;
                    var setupWidth = (float) LeftSide.PixelWidth;

                    if (1 - (setupWidth / actualWidth) > 0.30)
                    {
                        RightSide.Visible = false;
                    }

                    UserInterfaceManager.GetUIController<LobbyUIController>().ReloadCharacterSetup();

                    break;
            }
        }

        private void TogglePanel(bool value)
        {
            RightSide.Visible = value;
            ExpandPanel.Visible = !value;
        }

        public enum LobbyGuiState : byte
        {
            /// <summary>
            ///  The default state, i.e., what's seen on launch.
            /// </summary>
            Default,
            /// <summary>
            ///  The character setup state.
            /// </summary>
            CharacterSetup
        }
    }
}
