using System.Numerics;
using Robust.Shared.GameStates;

namespace Content.Shared.Weapons.Ranged.Components;

/// <summary>
/// Configures virtual crosshair recoil and recoil bloom for a ranged weapon.
/// </summary>
[RegisterComponent, NetworkedComponent, AutoGenerateComponentState]
public sealed partial class GunRecoilComponent : Component
{
    public const float DefaultKick = 0.5f;
    public const float DefaultMaxKick = 1f;
    public const float DefaultBaseSwayMultiplier = 1f;
    public const float DefaultRecoilKickMultiplier = 1f;
    public const float DefaultRecoverySpeed = 1f;
    public const float DefaultLateralKick = 0.035f;
    public const float DefaultSwayPenaltyPerShot = 0.035f;
    public const float DefaultShotgunSwayPenaltyPerShot = 0.14f;
    public const float DefaultMaxSwayPenalty = 0.45f;
    public const float DefaultSwayPenaltyDecay = 0.7f;
    public const float DefaultRecoilOffsetPerShot = 0.11f;
    public const float DefaultShotgunRecoilOffsetPerShot = 0.22f;
    public const float DefaultMaxRecoilOffset = 0.55f;
    public const float DefaultRecoilApproachRate = 28f;
    public const float DefaultRecoilRecoveryRate = 1.9f;

    /// <summary>
    /// Scalar applied to virtual recoil generated by this weapon.
    /// </summary>
    [DataField, AutoNetworkedField]
    public float Kick = DefaultKick;

    /// <summary>
    /// Weapon handling multiplier applied to base sway. Lower values are steadier.
    /// </summary>
    [DataField, AutoNetworkedField]
    public float BaseSwayMultiplier = DefaultBaseSwayMultiplier;

    /// <summary>
    /// Ergonomic recoil multiplier applied to kick and recoil bloom.
    /// </summary>
    [DataField, AutoNetworkedField]
    public float RecoilKickMultiplier = DefaultRecoilKickMultiplier;

    /// <summary>
    /// Recovery multiplier applied when recoil and bloom return to rest.
    /// </summary>
    [DataField, AutoNetworkedField]
    public float RecoverySpeed = DefaultRecoverySpeed;

    /// <summary>
    /// Random sideways kick added to the backwards virtual recoil.
     /// </summary>
    [DataField, AutoNetworkedField]
    public float LateralKick = DefaultLateralKick;

    /// <summary>
    /// Maximum virtual recoil vector length produced by a single shot.
    /// </summary>
    [DataField, AutoNetworkedField]
    public float MaxKick = DefaultMaxKick;

    /// <summary>
    /// Sway bloom added by a regular shot.
    /// </summary>
    [DataField, AutoNetworkedField]
    public float SwayPenaltyPerShot = DefaultSwayPenaltyPerShot;

    /// <summary>
    /// Sway bloom added by a spread-shot shell.
    /// </summary>
    [DataField, AutoNetworkedField]
    public float ShotgunSwayPenaltyPerShot = DefaultShotgunSwayPenaltyPerShot;

    /// <summary>
    /// Maximum accumulated sway bloom.
    /// </summary>
    [DataField, AutoNetworkedField]
    public float MaxSwayPenalty = DefaultMaxSwayPenalty;

    /// <summary>
    /// Amount of sway bloom recovered per second.
    /// </summary>
    [DataField, AutoNetworkedField]
    public float SwayPenaltyDecay = DefaultSwayPenaltyDecay;

    /// <summary>
    /// Virtual crosshair displacement added by a regular shot.
    /// </summary>
    [DataField, AutoNetworkedField]
    public float RecoilOffsetPerShot = DefaultRecoilOffsetPerShot;

    /// <summary>
    /// Virtual crosshair displacement added by a spread-shot shell.
    /// </summary>
    [DataField, AutoNetworkedField]
    public float ShotgunRecoilOffsetPerShot = DefaultShotgunRecoilOffsetPerShot;

    /// <summary>
    /// Maximum virtual crosshair recoil offset.
    /// </summary>
    [DataField, AutoNetworkedField]
    public float MaxRecoilOffset = DefaultMaxRecoilOffset;

    /// <summary>
    /// Spring rate used when the visible crosshair catches up to recoil.
    /// </summary>
    [DataField, AutoNetworkedField]
    public float RecoilApproachRate = DefaultRecoilApproachRate;

    /// <summary>
    /// Rate at which the recoil target returns to the mouse position.
    /// </summary>
    [DataField, AutoNetworkedField]
    public float RecoilRecoveryRate = DefaultRecoilRecoveryRate;

    /// <summary>
    /// Runtime sway bloom. Client-side for player feel, exposed for VV tuning.
    /// </summary>
    [ViewVariables(VVAccess.ReadWrite)]
    public float CurrentSwayPenalty;

    /// <summary>
    /// Runtime visible crosshair recoil offset.
    /// </summary>
    [ViewVariables(VVAccess.ReadWrite)]
    public Vector2 CurrentRecoilOffset;

    /// <summary>
    /// Runtime spring target for crosshair recoil.
    /// </summary>
    [ViewVariables(VVAccess.ReadWrite)]
    public Vector2 TargetRecoilOffset;
}
